### ISSUE TITLE
For training detail

### ISSUE THREAD

**Issue by sundongwei** [udrs/GCD#1]
It looks like not add train method(train.py). We are interested in your work, so could you please supply train.py detail.

**Comment by Hellen-master** [comment]
I'm also looking forward to more polished code from you and thank you for your generosity.

**Comment by udrs** [comment]
hi, the training file has been attached
I have not worked for the lab anymore. I dont have any time to maintain this project cause I worked in industy.
Thank you for your patience and understanding.
