### ISSUE TITLE
Where is the Noise Suppressor Module?

### ISSUE THREAD

**Issue by Billy-ZTB** [udrs/GCD#2]
I noticed that you introduced a Noise Suppression Module which uses FFT to suppress noise, but I didn't see it in the code. Could you please point out which line does this module lies in?

**Comment by cgy-01** [comment]
a class FFParser is defined in guided_difusion-unet-line463 ,maybe of some help

**Comment by Billy-ZTB** [comment]
Thanks! I've found it now.
